#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "vm" {
  source = "./module-vm-linux"

  azure_location                           = var.azure_location
  customer                                 = var.customer
  delete_os_disk_on_termination            = true
  disable_linux_password_authentification  = false
  disk_managed_type                        = "Standard_LRS"
  disk_name                                = "${var.customer}-${var.project}-${var.env}-disk"
  disk_size                                = 5
  env                                      = var.env
  file_content                             = ""
  image_id                                 = ""
  image_offer                              = "debian-10"
  image_publisher                          = "debian"
  image_sku                                = "10-cloudinit-gen2"
  image_version                            = "latest"
  instance_extra_tags                      = {}
  instance_name                            = "${var.customer}-${var.project}-${var.env}-vm"
  ip_config_name                           = "${var.customer}-${var.project}-${var.env}-ip_config"
  network_extra_tags                       = {}
  network_interface_name                   = "${var.customer}-${var.project}-${var.env}-nic"
  network_security_group_name              = "${var.customer}-${var.project}-${var.env}-sg"
  os_admin_password                        = "nico-secrets/password"
  os_admin_username                        = "nico-secrets/user"
  os_computer_name                         = "cycloid"
  project                                  = var.project
  public_ip_name                           = "${var.customer}-${var.project}-${var.env}-public_ip"
  resource_group_name                      = "rg-artistic-condor"
  security_rule_access                     = "Allow"
  security_rule_description                = "Enable SSH inbound traffic."
  security_rule_destination_address_prefix = "*"
  security_rule_destination_port_range     = "22"
  security_rule_direction                  = "Inbound"
  security_rule_name                       = "SSH"
  security_rule_priority                   = 1001
  security_rule_protocol                   = "Tcp"
  security_rule_source_address_prefix      = "*"
  security_rule_source_port_range          = "*"
  sg_extra_tags                            = {}
  subnet_id                                = ""
  vm_size                                  = "Standard_DS1_v2"
}

